# Generated by Django 2.1.1 on 2018-09-03 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='dateOfUpload',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
