# Generated by Django 2.1.1 on 2018-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_upload_dateofupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='Name not added', max_length=256),
        ),
    ]
